/*
 * generated by Xtext 2.40.0
 */
package gol.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

import gol.validation.GolValidator;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class GolQuickfixProvider extends DefaultQuickfixProvider {

//	@Fix(GolValidator.INVALID_NAME)
//	public void capitalizeName(final Issue issue, IssueResolutionAcceptor acceptor) {
//		acceptor.accept(issue, "Capitalize name", "Capitalize the name.", "upcase.png", new IModification() {
//			public void apply(IModificationContext context) throws BadLocationException {
//				IXtextDocument xtextDocument = context.getXtextDocument();
//				String firstLetter = xtextDocument.get(issue.getOffset(), 1);
//				xtextDocument.replace(issue.getOffset(), 1, firstLetter.toUpperCase());
//			}
//		});
//	}
	@Fix(GolValidator.DUPLICATE_CELL)
    public void removeDuplicateCell(Issue issue, IssueResolutionAcceptor acceptor) {

        acceptor.accept(
            issue,
            "Remove duplicate cell",
            "Removes the cell declared more than once at the same position.",
            null,
            (context) -> {
                context.getXtextDocument().replace(issue.getOffset(), issue.getLength(), "");
            }
        );
    }

}
