/*
 * generated by Xtext 2.40.0
 */
package gol.validation;

import gol.gol.Model;
import gol.gol.RuleKind;
import gol.gol.Operator;
import gol.gol.Cell;
import gol.gol.CellState;
import gol.gol.Rule;
import gol.gol.GolPackage;


import org.eclipse.xtext.validation.Check;
/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class GolValidator extends AbstractGolValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					GolPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
	@Check
	public void duplicate (Cell c) {
		Model model = (Model) c.eContainer();
		
		model.getCells().stream()
	        .filter(other -> other != c &&
	                other.getX() == c.getX() &&
	                other.getY() == c.getY())
	        .findAny()
	        .ifPresent(dup -> {
	            error(
	                "Duplicate cell at (" + c.getX() + ", " + c.getY() + ").",
	                GolPackage.Literals.CELL__X
	            );
	        });
	}

    @Check
    public void neighborRange(Rule r) {
        int v = r.getCondition().getValue();
        if (v < 0 || v > 8) {
            error(
                "A cell can only have between 0 and 8 neighbors.",
                GolPackage.Literals.CONDITION__VALUE
            );
        }
    }
    
    @Check
    public void wrongNeighbor(Rule r) {
        int v = r.getCondition().getValue();

        if (r.getKind() == RuleKind.SURVIVAL && (v < 0 || v > 8)) {
            error(
                "Survival rule has an impossible neighbor count.",
                GolPackage.Literals.RULE__KIND
            );
        }

        if (r.getKind() == RuleKind.BIRTH && (v < 0 || v > 8)) {
            error(
                "Birth rule has an impossible neighbor count.",
                GolPackage.Literals.RULE__KIND
            );
        }
    }
    
    @Check
    public void checkBirthDeathConflict(Model model) {

        var birthRules = model.getRules().stream()
                .filter(r -> r.getKind() == RuleKind.BIRTH)
                .toList();

        var deathRules = model.getRules().stream()
                .filter(r -> r.getKind() == RuleKind.DEATH)
                .toList();

        for (var b : birthRules) {
            for (var d : deathRules) {

                boolean sameOperator = b.getCondition().getOperator() == d.getCondition().getOperator();
                boolean sameValue = b.getCondition().getValue() == d.getCondition().getValue();

                if (sameOperator && sameValue) {

                    error(
                        "Conflict: A birth rule and a death rule use the same condition (" +
                        b.getCondition().getOperator().getLiteral() + " " +
                        b.getCondition().getValue() + ").",
                        GolPackage.Literals.RULE__KIND
                    );
                }
            }
        }
    }
}
